version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAtest2207gitProject
  gitServerName: Kusi_VCTest
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqatest2207git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQAtest2207gitProject
    version: "1.0"
- serviceName: project.siqatest2207git.integrations:SIQAAdapterFlow
  packages:
  - name: SIQAtest2207gitProject
    version: "1.0"
